### PR TITLE
[IMP] Add basic ACL

### PR DESCRIPTION
**Pull request by joaoalf**
This pull request adds basic ACL to the travel X purchase integration.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why last line put True/False instead of 1/0? I don't know if this is going to be parse correctly...

**Comment by joaoalf** [comment]
@pedrobaeza  Both ways work but I will change it to make the file more consistent.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by bwrsandman** [comment]
:+1:

**Pull request merged**
