### PR TITLE
[FIX] Remove dummy field for ref, use xmlid in view instead

### PR DESCRIPTION
**Pull request by yvaucher**
Fixup #12

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for fixing @yvaucher.

:+1:

**Comment by yvaucher** [comment]
I was curious as @pedrobaeza said it wasn't working so I tested locally got this:

capture du 2015-02-20 16 58 42

**Comment by pedrobaeza** [comment]
Yeah, sorry, I have also tested and I don't know how I overcame this. That was my initial intention when I tell Sandy that there's a better way for doing it, but I didn't say the exact formula for that.

Thanks for clarifying it.

**Comment by bwrsandman** [comment]
:+1: Thank you.

Do you know if there is a documentation for uses of `%(external_id)d` syntax somewhere?

**Comment by yvaucher** [comment]
@bwrsandman AFAIK this is only available in "grep documentation"... This is used in some official modules mostly in button names of type action.

**Pull request merged**
