### PR TITLE
[IMP] 7.0 - Add the journey as parameter to who and signer

### PR DESCRIPTION
**Pull request by ghost**
This allows to inherit the report more easily and customize the value of who and signer.

Also changed report_sxw.report_sxw to WebKitParser, because it is a webkit report, not RML. This causes failure in unit tests.

### CODE REVIEW

**Comment by bwrsandman** [comment]
:+1:

**Comment by ghost** [comment]
@bwrsandman 
What you are asking implies a major changing in these modules.
This can be done, but the whole report should be removed completely from https://github.com/OCA/vertical-travel. This report is something that is specific to the needs of one precise company.

Just take a look at the mako template for example
${_("thanks civilian and miliary authorities of the countries visited "
            "of the facilities they choose to equip bearer of this order for "
            "the smooth running of the mission.")}

**Comment by bwrsandman** [comment]
I am asking for two things:
1. use travel_journey_hr for the access rights pertaining to hr
2. fix the regression which was introduced in b74c575 (depending on hr)

The first issue blocks this PR, the second is important but not blocking. However if it stays, there is a high risk that this issue will grow.

**Comment by ghost** [comment]
@bwrsandman Fixed both things you asked for. Can you review please.

**Comment by bwrsandman** [comment]
Looks good! Thanks!

**Pull request closed without merging**
