### PR TITLE
[FIX] fixed rst description to avoid a traceback in the module form view

### PR DESCRIPTION
**Pull request by ccomb**
I was trying to travel vertically like a rocket when I suddenly got a traceback in the module form view, so I fixed the title to avoid burning in the atmosphere while returning back to earth

### CODE REVIEW

**Comment by max3903** [comment]
CLA fixed

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1: 

I fast track due to the severity.

**Comment by ccomb** [comment]
thx, awesome! It took less time to merge this PR than to load the airline_data.xml file! :)

**Pull request merged**
