### PR TITLE
[IMP] Basic ACLs

### PR DESCRIPTION
**Pull request by joaoalf**
- Filter journeys by travel AU on gantt and tree views

### CODE REVIEW

**Comment by pedrobaeza** [comment]
department_id is a user? You are equalling to uid.

**Comment by bwrsandman** [comment]
@pedrobaeza `department_rule` has a custom search function to restrict the user's employee according to the department. That's why it looks strange like that.

**Comment by pedrobaeza** [comment]
OK, thanks for the clarification.

:+1:

**Comment by bwrsandman** [comment]
No worries. Wish it could be simpler. Limitations of Odoo...

**Comment by bwrsandman** [comment]
:+1:

**Pull request merged**
